### ISSUE TITLE
Document the special Solr properties of the Catmandu::Store::Solr::Bag

### ISSUE THREAD

**Issue by phochste** [LibreCat/Catmandu-Solr#15]
E.g. it is an undocumented feature that extra parameters in the searcher are passed verbatim via the `searcher` to the backend Solr endpoint.

**Comment by nics** [comment]
Only the `search` method does this. The `searcher` accepts start, limit, sort, sort, total, fl.

**Comment by nics** [comment]
The synopsis now mentions this. The whole pod for the Solr store is badly in need of a rewrite.
